name: CI Backend- Main
on:
  push:
    branches:
      - '**' #qualquer barnchers
      - '!main' #exeto o principal
    paths:
      - 'sgcmapi/**'
workflow_dispatch:
workflow_call:
jobs:
  main: #primeirojob
    name: CI workflow Main #criar um job pra executar omainla de cima
    uses: ./.github/workflow/ci-backend.yml

  merge: #segundojob
    needs: main
    runs:-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Merge branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: main
          github_token: ${{ github_token }}
